// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnrEkD3QyoRUWuXcvgta1cHiCQGDodkNU',
    appId: '1:806155824999:web:f2b31ac9a5500f80a109c2',
    messagingSenderId: '806155824999',
    projectId: 'devis-facturation-gg-inter',
    authDomain: 'devis-facturation-gg-inter.firebaseapp.com',
    storageBucket: 'devis-facturation-gg-inter.firebasestorage.app',
    measurementId: 'G-GFKR4X1CY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY84Qmr7qXRmUQ8RvhVrw5EdqcBDRX9R0',
    appId: '1:806155824999:android:cab9cb817fd3dc6ca109c2',
    messagingSenderId: '806155824999',
    projectId: 'devis-facturation-gg-inter',
    storageBucket: 'devis-facturation-gg-inter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDflX5zAHbbZnE9B5ryYGPZ24yoGcppaFI',
    appId: '1:806155824999:ios:63ff9432895f3846a109c2',
    messagingSenderId: '806155824999',
    projectId: 'devis-facturation-gg-inter',
    storageBucket: 'devis-facturation-gg-inter.firebasestorage.app',
    iosBundleId: 'com.example.devisFactureGgIntervention',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDflX5zAHbbZnE9B5ryYGPZ24yoGcppaFI',
    appId: '1:806155824999:ios:63ff9432895f3846a109c2',
    messagingSenderId: '806155824999',
    projectId: 'devis-facturation-gg-inter',
    storageBucket: 'devis-facturation-gg-inter.firebasestorage.app',
    iosBundleId: 'com.example.devisFactureGgIntervention',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnrEkD3QyoRUWuXcvgta1cHiCQGDodkNU',
    appId: '1:806155824999:web:0687ea1da74bb73ca109c2',
    messagingSenderId: '806155824999',
    projectId: 'devis-facturation-gg-inter',
    authDomain: 'devis-facturation-gg-inter.firebaseapp.com',
    storageBucket: 'devis-facturation-gg-inter.firebasestorage.app',
    measurementId: 'G-JJ9H7RN9VC',
  );
}
